/*
Navicat Oracle Data Transfer
Oracle Client Version : 12.1.0.2.0

Source Server         : 10.0.100.183-dev
Source Server Version : 110200
Source Host           : 10.0.100.183:1521
Source Schema         : TRADE_GNNT

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2015-11-17 15:10:06
*/


-- ----------------------------
-- Table structure for V_SYSPARTITION
-- ----------------------------
DROP TABLE "TRADE_GNNT"."V_SYSPARTITION";
CREATE TABLE "TRADE_GNNT"."V_SYSPARTITION" (
"PARTITIONID" NUMBER(3) NOT NULL ,
"FIRMLIMITCLASS" VARCHAR2(256 BYTE) NOT NULL ,
"VALIDETCOMMODITYCLASS" VARCHAR2(256 BYTE) NOT NULL ,
"TRADERULECLASS" VARCHAR2(256 BYTE) NOT NULL ,
"BARGAINACTIONCLASS" VARCHAR2(256 BYTE) NOT NULL ,
"KERNELENGINECLASS" VARCHAR2(256 BYTE) NOT NULL ,
"COUNTDOWNCLASS" VARCHAR2(256 BYTE) NOT NULL ,
"VALIDFLAG" NUMBER(3) NOT NULL ,
"DESCRIPTION" VARCHAR2(128 BYTE) NULL ,
"TRADEMODE" NUMBER(3) NOT NULL ,
"SELFRATE" NUMBER(10) DEFAULT 0  NOT NULL ,
"ISSHOWQUOTATION" NUMBER(2) DEFAULT 0  NULL ,
"MAXSHOWQTY" NUMBER(5) DEFAULT 3  NOT NULL ,
"COUNTMODE" NUMBER(2) DEFAULT 0  NOT NULL ,
"ISMARGINCOUNT" NUMBER(2) DEFAULT 0  NOT NULL ,
"ISSPLITTARGET" NUMBER(2) DEFAULT 0  NOT NULL ,
"ISSHOWPRICE" NUMBER(2) DEFAULT 0  NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of V_SYSPARTITION
-- ----------------------------
INSERT INTO "TRADE_GNNT"."V_SYSPARTITION" VALUES ('1', 'gnnt.MEBS.vendue.front.service.impl.FirmLimitImpl', 'gnnt.MEBS.priceranking.server.tradeEngine.impl.ValidetCommodityForBuy', 'gnnt.MEBS.priceranking.server.tradeEngine.impl.TradeRuleForSplit', 'gnnt.MEBS.priceranking.server.tradeEngine.impl.TradeProcessForBuyImpl', 'gnnt.MEBS.priceranking.server.timeEngine.impl.KernelEngineImpl', 'gnnt.MEBS.priceranking.server.timeEngine.impl.CountDownEngineImpl', '1', '竞买', '1', '100', '0', '10', '0', '1', '1', '0');
INSERT INTO "TRADE_GNNT"."V_SYSPARTITION" VALUES ('2', 'gnnt.MEBS.vendue.front.service.impl.FirmLimitImpl', 'gnnt.MEBS.priceranking.server.tradeEngine.impl.ValidetCommodityForSell', 'gnnt.MEBS.priceranking.server.tradeEngine.impl.TradeRuleForSplit', 'gnnt.MEBS.priceranking.server.tradeEngine.impl.TradeProcessForSellImpl', 'gnnt.MEBS.priceranking.server.timeEngine.impl.KernelEngineImpl', 'gnnt.MEBS.priceranking.server.timeEngine.impl.CountDownEngineImpl', '1', '竞卖', '2', '100', '0', '3', '0', '0', '0', '0');
INSERT INTO "TRADE_GNNT"."V_SYSPARTITION" VALUES ('3', 'gnnt.MEBS.vendue.front.service.impl.FirmLimitImpl', 'gnnt.MEBS.priceranking.server.tradeEngine.impl.ValidetCommodityForBid', 'gnnt.MEBS.priceranking.server.tradeEngine.impl.TradeRuleForBid', 'gnnt.MEBS.priceranking.server.tradeEngine.impl.TradeProcessForBidImpl', 'gnnt.MEBS.priceranking.server.timeEngine.impl.KernelEngineImpl', 'gnnt.MEBS.priceranking.server.timeEngine.impl.CountDownEngineImpl', '1', '招标', '3', '100', '0', '3', '0', '0', '0', '0');

-- ----------------------------
-- Indexes structure for table V_SYSPARTITION
-- ----------------------------

-- ----------------------------
-- Checks structure for table V_SYSPARTITION
-- ----------------------------
ALTER TABLE "TRADE_GNNT"."V_SYSPARTITION" ADD CHECK ("PARTITIONID" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."V_SYSPARTITION" ADD CHECK ("FIRMLIMITCLASS" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."V_SYSPARTITION" ADD CHECK ("VALIDETCOMMODITYCLASS" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."V_SYSPARTITION" ADD CHECK ("TRADERULECLASS" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."V_SYSPARTITION" ADD CHECK ("BARGAINACTIONCLASS" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."V_SYSPARTITION" ADD CHECK ("KERNELENGINECLASS" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."V_SYSPARTITION" ADD CHECK ("COUNTDOWNCLASS" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."V_SYSPARTITION" ADD CHECK ("VALIDFLAG" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."V_SYSPARTITION" ADD CHECK ("TRADEMODE" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."V_SYSPARTITION" ADD CHECK ("SELFRATE" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."V_SYSPARTITION" ADD CHECK ("MAXSHOWQTY" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."V_SYSPARTITION" ADD CHECK ("COUNTMODE" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."V_SYSPARTITION" ADD CHECK ("ISMARGINCOUNT" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."V_SYSPARTITION" ADD CHECK ("ISSPLITTARGET" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."V_SYSPARTITION" ADD CHECK ("ISSHOWPRICE" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."V_SYSPARTITION" ADD CHECK ("PARTITIONID" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."V_SYSPARTITION" ADD CHECK ("FIRMLIMITCLASS" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."V_SYSPARTITION" ADD CHECK ("VALIDETCOMMODITYCLASS" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."V_SYSPARTITION" ADD CHECK ("TRADERULECLASS" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."V_SYSPARTITION" ADD CHECK ("BARGAINACTIONCLASS" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."V_SYSPARTITION" ADD CHECK ("KERNELENGINECLASS" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."V_SYSPARTITION" ADD CHECK ("COUNTDOWNCLASS" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."V_SYSPARTITION" ADD CHECK ("VALIDFLAG" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."V_SYSPARTITION" ADD CHECK ("TRADEMODE" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."V_SYSPARTITION" ADD CHECK ("SELFRATE" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."V_SYSPARTITION" ADD CHECK ("MAXSHOWQTY" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."V_SYSPARTITION" ADD CHECK ("COUNTMODE" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."V_SYSPARTITION" ADD CHECK ("ISMARGINCOUNT" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."V_SYSPARTITION" ADD CHECK ("ISSPLITTARGET" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."V_SYSPARTITION" ADD CHECK ("ISSHOWPRICE" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table V_SYSPARTITION
-- ----------------------------
ALTER TABLE "TRADE_GNNT"."V_SYSPARTITION" ADD PRIMARY KEY ("PARTITIONID");
