/*
Navicat Oracle Data Transfer
Oracle Client Version : 12.1.0.2.0

Source Server         : 10.0.100.183-dev
Source Server Version : 110200
Source Host           : 10.0.100.183:1521
Source Schema         : TRADE_GNNT

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2015-11-11 22:53:56
*/


-- ----------------------------
-- Table structure for L_MODULEANDAU
-- ----------------------------
DROP TABLE "TRADE_GNNT"."L_MODULEANDAU";
CREATE TABLE "TRADE_GNNT"."L_MODULEANDAU" (
"MODULEID" NUMBER(2) NOT NULL ,
"CONFIGID" NUMBER(6) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of L_MODULEANDAU
-- ----------------------------
INSERT INTO "TRADE_GNNT"."L_MODULEANDAU" VALUES ('10', '199001');
INSERT INTO "TRADE_GNNT"."L_MODULEANDAU" VALUES ('10', '210001');
INSERT INTO "TRADE_GNNT"."L_MODULEANDAU" VALUES ('10', '399001');
INSERT INTO "TRADE_GNNT"."L_MODULEANDAU" VALUES ('11', '199001');
INSERT INTO "TRADE_GNNT"."L_MODULEANDAU" VALUES ('11', '211001');
INSERT INTO "TRADE_GNNT"."L_MODULEANDAU" VALUES ('12', '499001');
INSERT INTO "TRADE_GNNT"."L_MODULEANDAU" VALUES ('13', '199001');
INSERT INTO "TRADE_GNNT"."L_MODULEANDAU" VALUES ('13', '213001');
INSERT INTO "TRADE_GNNT"."L_MODULEANDAU" VALUES ('14', '199001');
INSERT INTO "TRADE_GNNT"."L_MODULEANDAU" VALUES ('14', '214001');
INSERT INTO "TRADE_GNNT"."L_MODULEANDAU" VALUES ('15', '199001');
INSERT INTO "TRADE_GNNT"."L_MODULEANDAU" VALUES ('15', '215001');
INSERT INTO "TRADE_GNNT"."L_MODULEANDAU" VALUES ('15', '399001');
INSERT INTO "TRADE_GNNT"."L_MODULEANDAU" VALUES ('18', '199001');
INSERT INTO "TRADE_GNNT"."L_MODULEANDAU" VALUES ('18', '218001');
INSERT INTO "TRADE_GNNT"."L_MODULEANDAU" VALUES ('18', '399001');
INSERT INTO "TRADE_GNNT"."L_MODULEANDAU" VALUES ('18', '499001');
INSERT INTO "TRADE_GNNT"."L_MODULEANDAU" VALUES ('19', '199001');
INSERT INTO "TRADE_GNNT"."L_MODULEANDAU" VALUES ('21', '199001');
INSERT INTO "TRADE_GNNT"."L_MODULEANDAU" VALUES ('21', '221001');
INSERT INTO "TRADE_GNNT"."L_MODULEANDAU" VALUES ('28', '199001');
INSERT INTO "TRADE_GNNT"."L_MODULEANDAU" VALUES ('28', '228001');
INSERT INTO "TRADE_GNNT"."L_MODULEANDAU" VALUES ('29', '199001');
INSERT INTO "TRADE_GNNT"."L_MODULEANDAU" VALUES ('30', '199001');
INSERT INTO "TRADE_GNNT"."L_MODULEANDAU" VALUES ('30', '230001');
INSERT INTO "TRADE_GNNT"."L_MODULEANDAU" VALUES ('40', '199001');
INSERT INTO "TRADE_GNNT"."L_MODULEANDAU" VALUES ('40', '223001');
INSERT INTO "TRADE_GNNT"."L_MODULEANDAU" VALUES ('98', '199001');
INSERT INTO "TRADE_GNNT"."L_MODULEANDAU" VALUES ('98', '298001');
INSERT INTO "TRADE_GNNT"."L_MODULEANDAU" VALUES ('99', '199001');
INSERT INTO "TRADE_GNNT"."L_MODULEANDAU" VALUES ('99', '299001');
INSERT INTO "TRADE_GNNT"."L_MODULEANDAU" VALUES ('99', '399001');
INSERT INTO "TRADE_GNNT"."L_MODULEANDAU" VALUES ('99', '499001');

-- ----------------------------
-- Indexes structure for table L_MODULEANDAU
-- ----------------------------

-- ----------------------------
-- Checks structure for table L_MODULEANDAU
-- ----------------------------
ALTER TABLE "TRADE_GNNT"."L_MODULEANDAU" ADD CHECK ("MODULEID" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."L_MODULEANDAU" ADD CHECK ("CONFIGID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table L_MODULEANDAU
-- ----------------------------
ALTER TABLE "TRADE_GNNT"."L_MODULEANDAU" ADD PRIMARY KEY ("MODULEID", "CONFIGID");
