/*
Navicat Oracle Data Transfer
Oracle Client Version : 12.1.0.2.0

Source Server         : 10.0.100.183-dev
Source Server Version : 110200
Source Host           : 10.0.100.183:1521
Source Schema         : TRADE_GNNT

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2015-11-11 22:12:35
*/


-- ----------------------------
-- Table structure for C_LOGCATALOG
-- ----------------------------
DROP TABLE "TRADE_GNNT"."C_LOGCATALOG";
CREATE TABLE "TRADE_GNNT"."C_LOGCATALOG" (
"CATALOGID" NUMBER(4) NOT NULL ,
"MODULEID" NUMBER(2) NOT NULL ,
"CATALOGNAME" VARCHAR2(32 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "TRADE_GNNT"."C_LOGCATALOG" IS '日志分类，4位数字的编码，以日志模块ID开头。';
COMMENT ON COLUMN "TRADE_GNNT"."C_LOGCATALOG"."CATALOGID" IS '日志分类ID：4位数字的编码，详见备注Notes。';
COMMENT ON COLUMN "TRADE_GNNT"."C_LOGCATALOG"."MODULEID" IS '10综合管理平台
11财务系统
12监管仓库管理系统
13仓单管理系统
14融资系统
15订单交易
18投资类大宗商品交易系统
19加盟会员管理系统
20做市商交易系统
21竞价系统
22银行接入及结算系统
23E现货
24单点登录系统
25实时行情分析系统
26交易客户端
98demo系统
99公用系统';
COMMENT ON COLUMN "TRADE_GNNT"."C_LOGCATALOG"."CATALOGNAME" IS '日志分类名';

-- ----------------------------
-- Records of C_LOGCATALOG
-- ----------------------------
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('1001', '10', '角色管理日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('1011', '10', '管理员管理日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('1021', '10', '交易商管理日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('1031', '10', '交易员管理日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('1041', '10', '公告消息管理日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('1051', '10', '内容审核日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('1061', '10', '统计查询日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('1071', '10', '商品管理日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('1091', '10', '代为交易员日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('1101', '11', '凭证管理日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('1102', '11', '帐务查询日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('1103', '11', '交易商资金日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('1104', '11', '帐务维护日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('1300', '13', '交易核心错误日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('1301', '13', '交易核心信息日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('1310', '13', '仓单管理日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('1320', '13', '仓库管理日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('3201', '32', '前台登录管理');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('3202', '32', '前台修改密码管理');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('3203', '32', '后台登录管理');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('3204', '32', '后台修改密码');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('1901', '19', '加盟商后台日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('1910', '19', '加盟商前台公用日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('1915', '19', '加盟商前台订单日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('1501', '15', '订单交易核心信息日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('1502', '15', '订单交易核心错误日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('1503', '15', '订单运营管理日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('1504', '15', '订单交易参数设置日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('1505', '15', '订单交易商设置日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('1506', '15', '订单数据查询日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('1507', '15', '订单统计报表日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('1508', '15', '订单交收管理日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('1509', '15', '订单风险监控日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('1510', '15', '订单市场交易操作日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('1511', '15', '订单强制减仓日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('1512', '15', '订单系统维护日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('1513', '15', '订单延期交收日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('1514', '15', '订单加盟商佣金查询日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('9901', '99', '公用系统日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('2300', '23', '交易核心错误日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('2301', '23', '交易核心信息日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('2304', '23', '仲裁日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('2305', '23', '资金处理日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('2306', '23', '运营管理日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('2307', '23', '参数设置日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('2308', '23', '商品管理日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('2309', '23', '交易日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('2310', '23', '商铺管理日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('2320', '23', '统计查询日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('2101', '21', '竞价核心信息日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('2102', '21', '竞价核心错误日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('2103', '21', '竞价交易系统管理日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('2104', '21', '竞价交易商设置日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('2105', '21', '竞价商品管理日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('2106', '21', '竞价交易查询日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('2107', '21', '竞价报表查询日志');
INSERT INTO "TRADE_GNNT"."C_LOGCATALOG" VALUES ('2108', '21', '竞价合同管理日志');

-- ----------------------------
-- Indexes structure for table C_LOGCATALOG
-- ----------------------------

-- ----------------------------
-- Checks structure for table C_LOGCATALOG
-- ----------------------------
ALTER TABLE "TRADE_GNNT"."C_LOGCATALOG" ADD CHECK ("CATALOGID" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."C_LOGCATALOG" ADD CHECK ("MODULEID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table C_LOGCATALOG
-- ----------------------------
ALTER TABLE "TRADE_GNNT"."C_LOGCATALOG" ADD PRIMARY KEY ("CATALOGID");
